[pytest]
addopts = -v --html=report.html --self-contained-html
testpaths = tests
pythonpath = .

markers = 
    plogin : test 01 e2e login flow postive
    nlogin : test 02 e2e login flow negative
    pcheckout : test 03 e2e checkout flow postive
    ncheckout : test 04 e2e checkout flow postive